title: FADU
description: Feature Aggregate Depth Utility
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
markdown: kramdown
timezone: America/New_York
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
